import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CalendarDays, CheckCircle2, ClipboardCheck, FileText, Paperclip, Send, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const MAX_FILE_SIZE = 10 * 1024 * 1024;
function readFileAsDataUrl(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("Không đọc được file.")); reader.readAsDataURL(file); }); }

export default function Assignments() {
  const query = trpc.learning.listAssignments.useQuery();
  const utils = trpc.useUtils();
  const [selected, setSelected] = useState<number | null>(null);
  const [answer, setAnswer] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const active = query.data?.find(item => item.id === selected);
  const submit = trpc.learning.submitAssignment.useMutation({ onSuccess: async () => { toast.success("Bài làm và file đính kèm đã được nộp."); setAnswer(""); setFile(null); setSelected(null); await utils.learning.listAssignments.invalidate(); }, onError: error => toast.error(error.message) });
  const begin = (id: number) => { setSelected(id); setAnswer(""); setFile(null); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const send = async () => { if (!active || !answer.trim()) return; try { const attachmentData = file ? await readFileAsDataUrl(file) : undefined; submit.mutate({ assignmentId: active.id, answerText: answer, attachmentData, attachmentName: file?.name, attachmentType: file?.type }); } catch (error) { toast.error(error instanceof Error ? error.message : "Không thể đọc file."); } };
  return <DashboardLayout eyebrow="Theo dõi bài tập" title="Bài tập" description="Xem yêu cầu, hoàn thiện câu trả lời, đính kèm file và nộp bài ngay trong một luồng."><div className="mx-auto max-w-7xl">{active && <section className="mb-7 rounded-[26px] bg-[#163454] p-6 text-white shadow-xl shadow-[#163454]/10 md:p-8"><div className="flex items-start justify-between gap-5"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-[#a9d7c6]"><FileText size={15} /> Đang làm bài</div><h2 className="mt-3 font-display text-2xl font-bold">{active.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/65">{active.description}</p></div><button onClick={() => setSelected(null)} className="rounded-xl p-2 text-white/50 hover:bg-white/10 hover:text-white" aria-label="Đóng"><X size={18} /></button></div><div className="mt-6 rounded-2xl bg-white/10 p-4"><Textarea value={answer} onChange={e => setAnswer(e.target.value)} placeholder="Viết câu trả lời của bạn tại đây..." className="min-h-40 resize-y border-0 bg-transparent p-0 text-white placeholder:text-white/35 focus-visible:ring-0" /><div className="mt-4 flex flex-col justify-between gap-3 border-t border-white/10 pt-4 text-xs text-white/55 sm:flex-row sm:items-center"><label className="flex max-w-full cursor-pointer items-center gap-2 truncate text-white/70 hover:text-white"><Paperclip size={15} /><span className="truncate">{file ? file.name : "Đính kèm file (tối đa 10MB)"}</span><input type="file" className="sr-only" onChange={e => { const next = e.target.files?.[0]; if (next && next.size > MAX_FILE_SIZE) { toast.error("File đính kèm tối đa 10MB."); return; } setFile(next || null); }} /></label><Button disabled={submit.isPending || !answer.trim()} onClick={send} className="rounded-xl bg-[#f4c8bd] text-[#163454] hover:bg-[#f7d8d0]"><Send size={15} /> {submit.isPending ? "Đang nộp..." : "Nộp bài"}</Button></div></div></section>}
      <div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#e87560]">Danh sách</p><h2 className="mt-2 font-display text-2xl font-bold">Bài tập của bạn</h2></div><div className="flex items-center gap-2 rounded-full bg-white px-4 py-2 text-xs font-bold text-slate-500"><ClipboardCheck size={15} className="text-[#e87560]" /> {query.data?.length || 0} bài</div></div><div className="grid gap-4 md:grid-cols-2">{query.isLoading && [1,2,3,4].map(i => <div key={i} className="h-48 animate-pulse rounded-[24px] bg-white" />)}{query.data?.map(item => <AssignmentCard key={item.id} item={item} onStart={() => begin(item.id)} />)}{!query.isLoading && !query.data?.length && <div className="col-span-full rounded-[24px] bg-white p-12 text-center text-sm text-slate-400">Chưa có bài tập nào được giao.</div>}</div></div></DashboardLayout>;
}

function AssignmentCard({ item, onStart }: { item: any; onStart: () => void }) { const done = Boolean(item.submissionStatus); return <article className="rounded-[24px] border border-[#dbe3e0] bg-white p-6 transition-shadow hover:shadow-[0_14px_40px_rgba(22,52,84,0.07)]"><div className="flex items-start justify-between gap-4"><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${done ? "bg-[#dff1e9] text-[#398266]" : "bg-[#f8ddd6] text-[#e87560]"}`}><ClipboardCheck size={20} /></div><span className={`rounded-full px-3 py-1 text-[10px] font-bold ${done ? "bg-[#dff1e9] text-[#398266]" : "bg-[#f8ddd6] text-[#b9503e]"}`}>{done ? "Đã nộp" : "Chưa nộp"}</span></div><h3 className="mt-5 font-display text-xl font-bold">{item.title}</h3><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-500">{item.description}</p>{item.feedback && <div className="mt-4 rounded-xl bg-[#e8f1ed] p-3 text-xs leading-5 text-[#398266]"><strong>Phản hồi:</strong> {item.feedback}{typeof item.score === "number" ? ` · ${item.score} điểm` : ""}</div>}<div className="mt-5 flex flex-wrap items-center gap-3 text-xs font-semibold text-slate-400"><span className="flex items-center gap-1"><CalendarDays size={14} /> {item.dueAt ? new Date(item.dueAt).toLocaleDateString("vi-VN") : "Không đặt hạn"}</span><span>·</span><span>{item.maxScore} điểm</span>{item.attachmentName && <><span>·</span><span className="flex items-center gap-1"><Paperclip size={13} /> {item.attachmentName}</span></>}</div><Button onClick={onStart} className="mt-6 w-full rounded-xl bg-[#163454] text-white hover:bg-[#24476a]">{done ? "Nộp lại bài" : "Bắt đầu làm"} <ArrowRight size={16} /></Button>{done && <div className="mt-3 flex items-center gap-2 text-xs font-semibold text-[#398266]"><CheckCircle2 size={14} /> Bài đã được ghi nhận trên hệ thống</div>}</article>; }
